swagger: "2.0"
info:
    title: Ecommerce API
    description: Ecommerce API Design to Programming The Internet Class at BIU University
    contact:
        name: Adrison Gomez
        email: info@adrisongomez.me
        url: https://github.com/adrisongomez
    version: 0.0.1
host: localhost:3030
consumes:
    - application/json
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /api/healthcheck:
        get:
            tags:
                - svc-healthcheck
            summary: check svc-healthcheck
            operationId: svc-healthcheck#check
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/HealthcheckResponse'
            schemes:
                - http
    /api/openapi.json:
        get:
            tags:
                - openapi
            summary: Download internal/gen/http/openapi.json
            operationId: openapi#/api/openapi.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
    /api/products:
        get:
            tags:
                - svc-products
            summary: listProduct svc-products
            description: List products
            operationId: svc-products#listProduct
            parameters:
                - name: pageSize
                  in: query
                  description: Record per page
                  required: false
                  type: integer
                  default: 10
                  maximum: 100
                  minimum: 10
                - name: after
                  in: query
                  description: Start listing after this resource
                  required: false
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ProductsList'
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/SvcProductsListProductBadRequestResponseBody'
            schemes:
                - http
        post:
            tags:
                - svc-products
            summary: createProduct svc-products
            description: Create a new product
            operationId: svc-products#createProduct
            produces:
                - application/json
            parameters:
                - name: CreateProductRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/ProductInput'
                    required:
                        - title
                        - description
                        - tags
                        - vendorId
            responses:
                "201":
                    description: Created response.
                    schema:
                        $ref: '#/definitions/Product'
                "409":
                    description: Conflict response.
                    schema:
                        $ref: '#/definitions/SvcProductsCreateProductConflictResponseBody'
            schemes:
                - http
    /api/products/{productId}:
        get:
            tags:
                - svc-products
            summary: getProductById svc-products
            description: Get a product by its id
            operationId: svc-products#getProductById
            produces:
                - application/json
            parameters:
                - name: productId
                  in: path
                  description: Unique product identifier
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/Product'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/SvcProductsGetProductByIDNotFoundResponseBody'
            schemes:
                - http
        put:
            tags:
                - svc-products
            summary: deleteProductById svc-products
            description: Create a new product
            operationId: svc-products#deleteProductById
            parameters:
                - name: productId
                  in: path
                  description: Unique product identifier
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: boolean
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/SvcProductsDeleteProductByIDNotFoundResponseBody'
            schemes:
                - http
    /api/vendors:
        get:
            tags:
                - svc-vendor
            summary: list svc-vendor
            description: List vendors
            operationId: svc-vendor#list
            parameters:
                - name: pageSize
                  in: query
                  description: Record per page
                  required: false
                  type: integer
                  default: 10
                  maximum: 100
                  minimum: 10
                - name: after
                  in: query
                  description: Start listing after this resource
                  required: false
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/VendorList'
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/SvcVendorListBadRequestResponseBody'
            schemes:
                - http
        post:
            tags:
                - svc-vendor
            summary: create svc-vendor
            description: Create a new product
            operationId: svc-vendor#create
            parameters:
                - name: CreateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/VendorInput'
                    required:
                        - name
            responses:
                "201":
                    description: Created response.
                    schema:
                        $ref: '#/definitions/Vendor'
            schemes:
                - http
    /api/vendors/{vendorId}:
        put:
            tags:
                - svc-vendor
            summary: deleteById svc-vendor
            description: Create a new product
            operationId: svc-vendor#deleteById
            parameters:
                - name: vendorId
                  in: path
                  description: Unique product identifier
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: boolean
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/SvcVendorDeleteByIDNotFoundResponseBody'
            schemes:
                - http
definitions:
    HealthcheckResponse:
        title: 'Mediatype identifier: application/vnd.healthcheck-response+json; view=default'
        type: object
        properties:
            status:
                type: string
                example: Nulla aut sunt nobis sed qui vitae.
        description: CheckResponseBody result type (default view)
        example:
            status: Aspernatur deleniti et voluptate sunt.
    PageInfoResponseBody:
        title: 'Mediatype identifier: application/vnd.page-info+.json; view=default'
        type: object
        properties:
            endCursor:
                type: string
                description: The ending cursor for pagination
                example: Iure libero reiciendis quae aut repudiandae voluptatem.
            hasMore:
                type: boolean
                description: Indicates if there are more results available
                example: false
            startCursor:
                type: string
                description: The starting cursor for pagination
                example: Qui aut ipsum architecto.
            totalResource:
                type: integer
                description: Total number of resources available
                example: 7776217852295499949
                format: int64
        description: Pagination information (default view)
        example:
            endCursor: Tempore debitis voluptatum.
            hasMore: true
            startCursor: Ut eaque.
            totalResource: 7984555976830251701
        required:
            - startCursor
            - endCursor
            - hasMore
            - totalResource
    Product:
        title: 'Mediatype identifier: application/vnd.product+json; view=default'
        type: object
        properties:
            description:
                type: string
                description: Product description
                example: Cumque aut soluta hic.
            handle:
                type: string
                description: Handle
                example: Est totam.
            id:
                type: integer
                description: Key ID
                example: 10
                format: int64
                minimum: 1
            medias:
                type: array
                items:
                    $ref: '#/definitions/ProductMediaResponseBody'
                example:
                    - id: 10
                      mediaType: Facere sed qui.
                      url: Dolorem error voluptate molestiae blanditiis expedita qui.
                    - id: 10
                      mediaType: Facere sed qui.
                      url: Dolorem error voluptate molestiae blanditiis expedita qui.
                    - id: 10
                      mediaType: Facere sed qui.
                      url: Dolorem error voluptate molestiae blanditiis expedita qui.
            status:
                type: string
                description: The product's status on ecommerce site
                example: ACTIVE
                enum:
                    - ACTIVE
                    - DRAFT
            tags:
                type: array
                items:
                    type: string
                    example: Assumenda illum quibusdam labore similique aperiam.
                description: Product tags
                example:
                    - Qui inventore.
                    - Possimus repellat magni tempore asperiores blanditiis.
                    - Quisquam est rerum omnis.
                    - Deleniti in quia sint repudiandae.
            title:
                type: string
                description: Title
                example: Possimus eos ad et iste assumenda.
            variants:
                type: array
                items:
                    $ref: '#/definitions/ProductVariantResponseBody'
                example:
                    - colorHex: Tempore sit deserunt dolores.
                      colorName: Voluptatem et quia modi dolore.
                      featureMediaId: Omnis rerum molestiae omnis adipisci quidem laudantium.
                      id: 10
                      price: 7935072096624681393
                      productId: Eos praesentium ipsa.
                    - colorHex: Tempore sit deserunt dolores.
                      colorName: Voluptatem et quia modi dolore.
                      featureMediaId: Omnis rerum molestiae omnis adipisci quidem laudantium.
                      id: 10
                      price: 7935072096624681393
                      productId: Eos praesentium ipsa.
                    - colorHex: Tempore sit deserunt dolores.
                      colorName: Voluptatem et quia modi dolore.
                      featureMediaId: Omnis rerum molestiae omnis adipisci quidem laudantium.
                      id: 10
                      price: 7935072096624681393
                      productId: Eos praesentium ipsa.
            vendor:
                $ref: '#/definitions/VendorResponseBody'
        description: GetProductByIdResponseBody result type (default view)
        example:
            description: Voluptatibus laudantium iusto debitis nihil.
            handle: Repellendus soluta ut.
            id: 10
            medias:
                - id: 10
                  mediaType: Facere sed qui.
                  url: Dolorem error voluptate molestiae blanditiis expedita qui.
                - id: 10
                  mediaType: Facere sed qui.
                  url: Dolorem error voluptate molestiae blanditiis expedita qui.
                - id: 10
                  mediaType: Facere sed qui.
                  url: Dolorem error voluptate molestiae blanditiis expedita qui.
            status: ACTIVE
            tags:
                - Saepe autem non vel aut asperiores aut.
                - Laborum odio sunt optio enim corporis.
                - Laboriosam eveniet voluptas molestiae.
                - Facilis neque vero.
            title: Fuga iste aut est eos eos.
            variants:
                - colorHex: Tempore sit deserunt dolores.
                  colorName: Voluptatem et quia modi dolore.
                  featureMediaId: Omnis rerum molestiae omnis adipisci quidem laudantium.
                  id: 10
                  price: 7935072096624681393
                  productId: Eos praesentium ipsa.
                - colorHex: Tempore sit deserunt dolores.
                  colorName: Voluptatem et quia modi dolore.
                  featureMediaId: Omnis rerum molestiae omnis adipisci quidem laudantium.
                  id: 10
                  price: 7935072096624681393
                  productId: Eos praesentium ipsa.
            vendor:
                id: 10
                name: Blanditiis deserunt quis suscipit.
        required:
            - id
            - title
            - handle
            - description
            - status
    ProductInput:
        title: ProductInput
        type: object
        properties:
            description:
                type: string
                description: Product description
                example: Blanditiis architecto.
            handle:
                type: string
                description: Last part of the url which use to idepntify the user
                example: Accusantium nemo sunt distinctio placeat fugit aut.
            medias:
                type: array
                items:
                    $ref: '#/definitions/ProductMediaInput'
                example:
                    - alt: Tenetur qui consequuntur.
                      mediaId: Soluta animi aliquam eaque et.
                      sortNumber: 6570939598249231544
                    - alt: Tenetur qui consequuntur.
                      mediaId: Soluta animi aliquam eaque et.
                      sortNumber: 6570939598249231544
            status:
                type: string
                description: Product's status
                example: DRAFT
                enum:
                    - ACTIVE
                    - DRAFT
            tags:
                type: array
                items:
                    type: string
                    example: Et nostrum sit fugit dolores.
                description: Product tags
                example:
                    - Inventore eaque et.
                    - Ea eos rem incidunt fuga.
                    - Ducimus voluptatum fugit.
                    - Voluptas qui quod quam sunt.
            title:
                type: string
                description: Title's product
                example: Maiores perspiciatis eos itaque repudiandae sit.
            variants:
                type: array
                items:
                    $ref: '#/definitions/ProductVariantInput'
                description: Product variants
                example:
                    - colorHex: Numquam ad.
                      colorName: Impedit sequi.
                      price: 5605191480377568692
                    - colorHex: Numquam ad.
                      colorName: Impedit sequi.
                      price: 5605191480377568692
            vendorId:
                type: string
                description: Vendor's product
                example: Consequuntur neque repellat id praesentium soluta.
        example:
            description: Deserunt ut explicabo non repellat doloribus dolor.
            handle: Asperiores neque non accusantium ex autem.
            medias:
                - alt: Tenetur qui consequuntur.
                  mediaId: Soluta animi aliquam eaque et.
                  sortNumber: 6570939598249231544
                - alt: Tenetur qui consequuntur.
                  mediaId: Soluta animi aliquam eaque et.
                  sortNumber: 6570939598249231544
            status: DRAFT
            tags:
                - Et mollitia nam.
                - Itaque ut pariatur id.
            title: Et fugiat enim rem quos.
            variants:
                - colorHex: Numquam ad.
                  colorName: Impedit sequi.
                  price: 5605191480377568692
                - colorHex: Numquam ad.
                  colorName: Impedit sequi.
                  price: 5605191480377568692
                - colorHex: Numquam ad.
                  colorName: Impedit sequi.
                  price: 5605191480377568692
            vendorId: Architecto placeat est id unde delectus consequatur.
        required:
            - title
            - description
            - tags
            - vendorId
    ProductMediaInput:
        title: ProductMediaInput
        type: object
        properties:
            alt:
                type: string
                description: Alt text that would show in case the image does not render
                example: Rerum amet occaecati quia nam qui.
            mediaId:
                type: string
                description: ID of the media record where the resource has being upload
                example: Ullam molestias animi et necessitatibus a aut.
            sortNumber:
                type: integer
                description: Position on the images of the product
                example: 2007185614006316366
                format: int64
        example:
            alt: Commodi asperiores.
            mediaId: Numquam qui ut rerum cupiditate et.
            sortNumber: 3912813882709573896
        required:
            - mediaId
            - sortNumber
    ProductMediaResponseBody:
        title: 'Mediatype identifier: application/vnd.product-media+json; view=default'
        type: object
        properties:
            id:
                type: integer
                description: Key ID
                example: 10
                format: int64
                minimum: 1
            mediaType:
                type: string
                example: Modi aut facere.
            url:
                type: string
                description: URL to the media
                example: Veniam voluptatem sit.
        description: Product-MediaResponseBody result type (default view)
        example:
            id: 10
            mediaType: Dicta alias.
            url: Doloribus et.
    ProductResponseBody:
        title: 'Mediatype identifier: application/vnd.product+json; view=default'
        type: object
        properties:
            description:
                type: string
                description: Product description
                example: Voluptatem sequi tempora consequatur libero.
            handle:
                type: string
                description: Handle
                example: Necessitatibus non voluptatem qui explicabo.
            id:
                type: integer
                description: Key ID
                example: 10
                format: int64
                minimum: 1
            medias:
                type: array
                items:
                    $ref: '#/definitions/ProductMediaResponseBody'
                example:
                    - id: 10
                      mediaType: Facere sed qui.
                      url: Dolorem error voluptate molestiae blanditiis expedita qui.
                    - id: 10
                      mediaType: Facere sed qui.
                      url: Dolorem error voluptate molestiae blanditiis expedita qui.
                    - id: 10
                      mediaType: Facere sed qui.
                      url: Dolorem error voluptate molestiae blanditiis expedita qui.
                    - id: 10
                      mediaType: Facere sed qui.
                      url: Dolorem error voluptate molestiae blanditiis expedita qui.
            status:
                type: string
                description: The product's status on ecommerce site
                example: DRAFT
                enum:
                    - ACTIVE
                    - DRAFT
            tags:
                type: array
                items:
                    type: string
                    example: Aut et itaque et.
                description: Product tags
                example:
                    - Sit porro laudantium repellendus autem.
                    - Dolor illum asperiores sit ea est quisquam.
                    - Deserunt maxime error accusantium ut velit ut.
                    - Animi mollitia voluptatibus.
            title:
                type: string
                description: Title
                example: Eius ut dolores.
            variants:
                type: array
                items:
                    $ref: '#/definitions/ProductVariantResponseBody'
                example:
                    - colorHex: Tempore sit deserunt dolores.
                      colorName: Voluptatem et quia modi dolore.
                      featureMediaId: Omnis rerum molestiae omnis adipisci quidem laudantium.
                      id: 10
                      price: 7935072096624681393
                      productId: Eos praesentium ipsa.
                    - colorHex: Tempore sit deserunt dolores.
                      colorName: Voluptatem et quia modi dolore.
                      featureMediaId: Omnis rerum molestiae omnis adipisci quidem laudantium.
                      id: 10
                      price: 7935072096624681393
                      productId: Eos praesentium ipsa.
                    - colorHex: Tempore sit deserunt dolores.
                      colorName: Voluptatem et quia modi dolore.
                      featureMediaId: Omnis rerum molestiae omnis adipisci quidem laudantium.
                      id: 10
                      price: 7935072096624681393
                      productId: Eos praesentium ipsa.
            vendor:
                $ref: '#/definitions/VendorResponseBody'
        description: Product information (default view)
        example:
            description: Maxime qui quasi aspernatur dolorem.
            handle: Consequuntur animi repellat enim nihil.
            id: 10
            medias:
                - id: 10
                  mediaType: Facere sed qui.
                  url: Dolorem error voluptate molestiae blanditiis expedita qui.
                - id: 10
                  mediaType: Facere sed qui.
                  url: Dolorem error voluptate molestiae blanditiis expedita qui.
                - id: 10
                  mediaType: Facere sed qui.
                  url: Dolorem error voluptate molestiae blanditiis expedita qui.
            status: DRAFT
            tags:
                - Provident non quibusdam.
                - Eum iste.
            title: Qui rerum qui.
            variants:
                - colorHex: Tempore sit deserunt dolores.
                  colorName: Voluptatem et quia modi dolore.
                  featureMediaId: Omnis rerum molestiae omnis adipisci quidem laudantium.
                  id: 10
                  price: 7935072096624681393
                  productId: Eos praesentium ipsa.
                - colorHex: Tempore sit deserunt dolores.
                  colorName: Voluptatem et quia modi dolore.
                  featureMediaId: Omnis rerum molestiae omnis adipisci quidem laudantium.
                  id: 10
                  price: 7935072096624681393
                  productId: Eos praesentium ipsa.
                - colorHex: Tempore sit deserunt dolores.
                  colorName: Voluptatem et quia modi dolore.
                  featureMediaId: Omnis rerum molestiae omnis adipisci quidem laudantium.
                  id: 10
                  price: 7935072096624681393
                  productId: Eos praesentium ipsa.
                - colorHex: Tempore sit deserunt dolores.
                  colorName: Voluptatem et quia modi dolore.
                  featureMediaId: Omnis rerum molestiae omnis adipisci quidem laudantium.
                  id: 10
                  price: 7935072096624681393
                  productId: Eos praesentium ipsa.
            vendor:
                id: 10
                name: Blanditiis deserunt quis suscipit.
        required:
            - id
            - title
            - handle
            - description
            - status
    ProductResponseBodyCollection:
        title: 'Mediatype identifier: application/vnd.product+json; type=collection; view=default'
        type: array
        items:
            $ref: '#/definitions/ProductResponseBody'
        description: ProductCollectionResponseBody is the result type for an array of ProductResponseBody (default view)
        example:
            - description: At magni eaque quia.
              handle: Voluptas nostrum est a error.
              id: 10
              medias:
                - id: 10
                  mediaType: Facere sed qui.
                  url: Dolorem error voluptate molestiae blanditiis expedita qui.
                - id: 10
                  mediaType: Facere sed qui.
                  url: Dolorem error voluptate molestiae blanditiis expedita qui.
                - id: 10
                  mediaType: Facere sed qui.
                  url: Dolorem error voluptate molestiae blanditiis expedita qui.
              status: ACTIVE
              tags:
                - Quod facilis quod impedit et tempora libero.
                - Laboriosam eum dicta.
              title: A reprehenderit.
              variants:
                - colorHex: Tempore sit deserunt dolores.
                  colorName: Voluptatem et quia modi dolore.
                  featureMediaId: Omnis rerum molestiae omnis adipisci quidem laudantium.
                  id: 10
                  price: 7935072096624681393
                  productId: Eos praesentium ipsa.
                - colorHex: Tempore sit deserunt dolores.
                  colorName: Voluptatem et quia modi dolore.
                  featureMediaId: Omnis rerum molestiae omnis adipisci quidem laudantium.
                  id: 10
                  price: 7935072096624681393
                  productId: Eos praesentium ipsa.
              vendor:
                id: 10
                name: Blanditiis deserunt quis suscipit.
            - description: At magni eaque quia.
              handle: Voluptas nostrum est a error.
              id: 10
              medias:
                - id: 10
                  mediaType: Facere sed qui.
                  url: Dolorem error voluptate molestiae blanditiis expedita qui.
                - id: 10
                  mediaType: Facere sed qui.
                  url: Dolorem error voluptate molestiae blanditiis expedita qui.
                - id: 10
                  mediaType: Facere sed qui.
                  url: Dolorem error voluptate molestiae blanditiis expedita qui.
              status: ACTIVE
              tags:
                - Quod facilis quod impedit et tempora libero.
                - Laboriosam eum dicta.
              title: A reprehenderit.
              variants:
                - colorHex: Tempore sit deserunt dolores.
                  colorName: Voluptatem et quia modi dolore.
                  featureMediaId: Omnis rerum molestiae omnis adipisci quidem laudantium.
                  id: 10
                  price: 7935072096624681393
                  productId: Eos praesentium ipsa.
                - colorHex: Tempore sit deserunt dolores.
                  colorName: Voluptatem et quia modi dolore.
                  featureMediaId: Omnis rerum molestiae omnis adipisci quidem laudantium.
                  id: 10
                  price: 7935072096624681393
                  productId: Eos praesentium ipsa.
              vendor:
                id: 10
                name: Blanditiis deserunt quis suscipit.
    ProductVariantInput:
        title: ProductVariantInput
        type: object
        properties:
            colorHex:
                type: string
                description: Color in HEX value that would be used on the variant picker
                example: Distinctio est.
            colorName:
                type: string
                description: Color variant option
                example: Expedita expedita dolorum ex saepe a ex.
            price:
                type: integer
                description: Price on cents
                example: 7019682821450365712
                format: int64
        example:
            colorHex: Nam accusantium magnam nesciunt debitis.
            colorName: Ut eum est eos.
            price: 5435801383477123509
        required:
            - colorName
            - price
    ProductVariantResponseBody:
        title: 'Mediatype identifier: application/vnd.product-variant+json; view=default'
        type: object
        properties:
            colorHex:
                type: string
                description: Color in HEX value that would be used on the variant picker
                example: Sed nam molestiae quia occaecati laboriosam qui.
            colorName:
                type: string
                description: Color variant option
                example: Molestias ad enim hic.
            featureMediaId:
                type: string
                description: ProductMedia which would be focus when a variant is picked by the user
                example: Qui quidem et dolor et cumque sed.
            id:
                type: integer
                description: Key ID
                example: 10
                format: int64
                minimum: 1
            price:
                type: integer
                description: Price on cents
                example: 1219544057631634519
                format: int64
            productId:
                type: string
                description: Product where the variant belongs to
                example: Voluptates nisi eveniet.
        description: Definition of product variants (default view)
        example:
            colorHex: Incidunt corrupti et sapiente voluptatem sit.
            colorName: Corrupti facilis mollitia iste vel ut iure.
            featureMediaId: Laudantium explicabo provident consequatur saepe facere id.
            id: 10
            price: 8385608967186261681
            productId: Ea id earum eligendi dolorum eum.
    ProductsList:
        title: 'Mediatype identifier: application/vnd.products-list+json; view=default'
        type: object
        properties:
            data:
                $ref: '#/definitions/ProductResponseBodyCollection'
            pageInfo:
                $ref: '#/definitions/PageInfoResponseBody'
        description: ListProductResponseBody result type (default view)
        example:
            data:
                - description: At magni eaque quia.
                  handle: Voluptas nostrum est a error.
                  id: 10
                  medias:
                    - id: 10
                      mediaType: Facere sed qui.
                      url: Dolorem error voluptate molestiae blanditiis expedita qui.
                    - id: 10
                      mediaType: Facere sed qui.
                      url: Dolorem error voluptate molestiae blanditiis expedita qui.
                    - id: 10
                      mediaType: Facere sed qui.
                      url: Dolorem error voluptate molestiae blanditiis expedita qui.
                  status: ACTIVE
                  tags:
                    - Quod facilis quod impedit et tempora libero.
                    - Laboriosam eum dicta.
                  title: A reprehenderit.
                  variants:
                    - colorHex: Tempore sit deserunt dolores.
                      colorName: Voluptatem et quia modi dolore.
                      featureMediaId: Omnis rerum molestiae omnis adipisci quidem laudantium.
                      id: 10
                      price: 7935072096624681393
                      productId: Eos praesentium ipsa.
                    - colorHex: Tempore sit deserunt dolores.
                      colorName: Voluptatem et quia modi dolore.
                      featureMediaId: Omnis rerum molestiae omnis adipisci quidem laudantium.
                      id: 10
                      price: 7935072096624681393
                      productId: Eos praesentium ipsa.
                  vendor:
                    id: 10
                    name: Blanditiis deserunt quis suscipit.
                - description: At magni eaque quia.
                  handle: Voluptas nostrum est a error.
                  id: 10
                  medias:
                    - id: 10
                      mediaType: Facere sed qui.
                      url: Dolorem error voluptate molestiae blanditiis expedita qui.
                    - id: 10
                      mediaType: Facere sed qui.
                      url: Dolorem error voluptate molestiae blanditiis expedita qui.
                    - id: 10
                      mediaType: Facere sed qui.
                      url: Dolorem error voluptate molestiae blanditiis expedita qui.
                  status: ACTIVE
                  tags:
                    - Quod facilis quod impedit et tempora libero.
                    - Laboriosam eum dicta.
                  title: A reprehenderit.
                  variants:
                    - colorHex: Tempore sit deserunt dolores.
                      colorName: Voluptatem et quia modi dolore.
                      featureMediaId: Omnis rerum molestiae omnis adipisci quidem laudantium.
                      id: 10
                      price: 7935072096624681393
                      productId: Eos praesentium ipsa.
                    - colorHex: Tempore sit deserunt dolores.
                      colorName: Voluptatem et quia modi dolore.
                      featureMediaId: Omnis rerum molestiae omnis adipisci quidem laudantium.
                      id: 10
                      price: 7935072096624681393
                      productId: Eos praesentium ipsa.
                  vendor:
                    id: 10
                    name: Blanditiis deserunt quis suscipit.
                - description: At magni eaque quia.
                  handle: Voluptas nostrum est a error.
                  id: 10
                  medias:
                    - id: 10
                      mediaType: Facere sed qui.
                      url: Dolorem error voluptate molestiae blanditiis expedita qui.
                    - id: 10
                      mediaType: Facere sed qui.
                      url: Dolorem error voluptate molestiae blanditiis expedita qui.
                    - id: 10
                      mediaType: Facere sed qui.
                      url: Dolorem error voluptate molestiae blanditiis expedita qui.
                  status: ACTIVE
                  tags:
                    - Quod facilis quod impedit et tempora libero.
                    - Laboriosam eum dicta.
                  title: A reprehenderit.
                  variants:
                    - colorHex: Tempore sit deserunt dolores.
                      colorName: Voluptatem et quia modi dolore.
                      featureMediaId: Omnis rerum molestiae omnis adipisci quidem laudantium.
                      id: 10
                      price: 7935072096624681393
                      productId: Eos praesentium ipsa.
                    - colorHex: Tempore sit deserunt dolores.
                      colorName: Voluptatem et quia modi dolore.
                      featureMediaId: Omnis rerum molestiae omnis adipisci quidem laudantium.
                      id: 10
                      price: 7935072096624681393
                      productId: Eos praesentium ipsa.
                  vendor:
                    id: 10
                    name: Blanditiis deserunt quis suscipit.
            pageInfo:
                endCursor: Repellat praesentium voluptas sint voluptas debitis.
                hasMore: false
                startCursor: Quis deleniti et itaque sapiente debitis.
                totalResource: 3611108466135392965
    SvcProductsCreateProductConflictResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: createProduct_Conflict_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    SvcProductsDeleteProductByIDNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: deleteProductById_NotFound_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    SvcProductsGetProductByIDNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: getProductById_NotFound_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    SvcProductsListProductBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: listProduct_BadRequest_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    SvcProductsUpdateProductByIDConflictResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: updateProductById_Conflict_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    SvcVendorDeleteByIDNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: deleteById_NotFound_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    SvcVendorListBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: list_BadRequest_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    Vendor:
        title: 'Mediatype identifier: application/vnd.vendor+json; view=default'
        type: object
        properties:
            id:
                type: integer
                description: Key ID
                example: 10
                format: int64
                minimum: 1
            name:
                type: string
                example: Aut quia tempora aut ut.
        description: CreateResponseBody result type (default view)
        example:
            id: 10
            name: Ut harum quos architecto.
        required:
            - name
    VendorInput:
        title: VendorInput
        type: object
        properties:
            name:
                type: string
                example: Culpa et quisquam.
        example:
            name: Rerum vel numquam illum culpa possimus atque.
        required:
            - name
    VendorList:
        title: 'Mediatype identifier: application/vnd.vendor-list+json; view=default'
        type: object
        properties:
            data:
                $ref: '#/definitions/VendorResponseBodyCollection'
            pageInfo:
                $ref: '#/definitions/PageInfoResponseBody'
        description: ListResponseBody result type (default view)
        example:
            data:
                - id: 10
                  name: Blanditiis deserunt quis suscipit.
                - id: 10
                  name: Blanditiis deserunt quis suscipit.
                - id: 10
                  name: Blanditiis deserunt quis suscipit.
            pageInfo:
                endCursor: Repellat praesentium voluptas sint voluptas debitis.
                hasMore: false
                startCursor: Quis deleniti et itaque sapiente debitis.
                totalResource: 3611108466135392965
    VendorResponseBody:
        title: 'Mediatype identifier: application/vnd.vendor+json; view=default'
        type: object
        properties:
            id:
                type: integer
                description: Key ID
                example: 10
                format: int64
                minimum: 1
            name:
                type: string
                example: Dolor sit at.
        description: VendorResponseBody result type (default view)
        example:
            id: 10
            name: Repudiandae et ab culpa corporis exercitationem.
        required:
            - name
    VendorResponseBodyCollection:
        title: 'Mediatype identifier: application/vnd.vendor+json; type=collection; view=default'
        type: array
        items:
            $ref: '#/definitions/VendorResponseBody'
        description: VendorCollectionResponseBody is the result type for an array of VendorResponseBody (default view)
        example:
            - id: 10
              name: Blanditiis deserunt quis suscipit.
            - id: 10
              name: Blanditiis deserunt quis suscipit.
